name: Vulnerability Scan (On-Demand)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Repo Tag and Docker image to scan"
        required: true
        default: "v1.0.0"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  scan:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan Dockerfile (config)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: config
          scan-ref: ./src
          format: sarif
          output: vulnerability-config-results.sarif

      - name: Upload vulnerability config scan results to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: vulnerability-config-results.sarif
          category: vulnerability-config

      - name: Scan built image (image)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.image_tag }}
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: sarif
          output: vulnerability-image-results.sarif

      - name: Upload vulnerability image scan results to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: vulnerability-image-results.sarif
          category: vulnerability-image